name: Python CICD

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run_test:
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Setup Python
        uses: action/checkout@v4
        with:
          python-version: "3.15.0-alpha.2"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Run tests with coverage and html report 
        run: pytest --cov=, --cov-retport=term --cov-report=xml --html=report.html \
      
