name: Python CICD

on:
  push:
    branches: [ development ]
  pull_request:

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.15.0-alpha.2"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage + HTML
        run: pytest --cov=. --cov-report=term --cov-report=xml --cov-report=html

      - name: Prepare artifact folder
        run: |
          mkdir sites
          mv htmlcov sites/
          mv coverage.xml sites/

      - name: Upload artifact
        uses: action/Upload-artifact@v4
        with:
          name: coverage-report
          path: site
      
